export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const LOGOUT = "LOGOUT";
export const LOGOUT_FAIL = "LOGOUT_FAIL";
export const AUTHENTICATED = "AUTHENTICATED";
export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_VERIFICATION_SUCCESS = "SIGNUP_VERIFICATION_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";
export const SIGNUP_VERIFICATION_FAILED = "SIGNUP_VERIFICATION_FAILED";

export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAIL = "FETCH_PRODUCTS_FAIL";
export const SHOW_PRODUCT_SUCCESS = "SHOW_PRODUCT_SUCCESS";
export const SHOW_PRODUCT_FAIL = "SHOW_PRODUCT_FAIL";
