export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const LOGOUT = "LOGOUT";
export const LOGOUT_FAIL = "LOGOUT_FAIL";
export const AUTHENTICATED = "AUTHENTICATED";
export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_VERIFICATION_SUCCESS = "SIGNUP_VERIFICATION_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";
export const SIGNUP_VERIFICATION_FAILED = "SIGNUP_VERIFICATION_FAILED";

export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAIL = "FETCH_PRODUCTS_FAIL";
export const SHOW_PRODUCT_SUCCESS = "SHOW_PRODUCT_SUCCESS";
export const SHOW_PRODUCT_FAIL = "SHOW_PRODUCT_FAIL";

export const SET_PRODUCT_INFO_TO_NULL = "SET_PRODUCT_INFO_TO_NULL";

export const FETCH_SEARCHED_PRODUCTS_SUCCESS =
  "FETCH_SEARCHED_PRODUCTS_SUCCESS";
export const FETCH_SEARCHED_PRODUCTS_FAIL = "FETCH_SEARCHED_PRODUCTS_FAIL";
export const SHOW_SEARCHED_PRODUCTS_SUCCESS = "SHOW_SEARCHED_PRODUCTS_SUCCESS";
export const SHOW_SEARCHED_PRODUCTS_FAIL = "SHOW_SEARCHED_PRODUCTS_FAIL";

export const FETCH_BRANDS_SUCCESS = "FETCH_BRANDS_SUCCESS";
export const FETCH_BRANDS_FAIL = "FETCH_BRANDS_FAIL";

export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const FETCH_CATEGORIES_FAIL = "FETCH_CATEGORIES_FAIL";

export const START_ACTION_CABLE_SUCCESS = "START_ACTION_CABLE_SUCCESS";
export const START_ACTION_CABLE_FAIL = "START_ACTION_CABLE_FAIL";

export const SAVE_CART = "SAVE_CART";
export const SAVE_CART_PRODUCT_SUCCESS = "SAVE_CART_PRODUCT_SUCCESS";
export const SAVE_CART_PRODUCT_FAIL = "SAVE_CART_PRODUCT_FAIL";
export const SAVE_TOTAL_CART_PRICE = "SAVE_TOTAL_CART_PRICE";

export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";

export const FETCH_ORDERS = "FETCH_ORDERS";
